import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [response, setResponse] = useState(null);

  async function request(endpoint) {
    const headers = new Headers();
    headers.append("x-api-key", "some-key");
    headers.append("x-country-id", 484);
    headers.append("x-region-id", 1);

    const requestResponse = await fetch(endpoint, {
      method: "GET",
      headers,
    });

    const jsonResponse = await requestResponse.json();

    setResponse({
      endpoint,
      response: jsonResponse,
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CORS Example </h1>

        <div>
          <p>
            <span>Same domain</span>
            &nbsp;=&nbsp;
            <a href="#" onClick={() => request("/api/posts/1")}>
              Post 1
            </a>
            &nbsp;|&nbsp;
            <a href="#" onClick={() => request("/api/posts/2")}>
              Post 2
            </a>
            &nbsp;|&nbsp;
            <a href="#" onClick={() => request("/api/posts/3")}>
              Post 3
            </a>
          </p>

          <p>
            <span>Different domain</span>
            &nbsp;=&nbsp;
            <a
              href="#"
              onClick={() =>
                request("https://jsonplaceholder.typicode.com/posts/1")
              }
            >
              Post 1
            </a>
            &nbsp;|&nbsp;
            <a
              href="#"
              onClick={() =>
                request("https://jsonplaceholder.typicode.com/posts/2")
              }
            >
              Post 2
            </a>
            &nbsp;|&nbsp;
            <a
              href="#"
              onClick={() =>
                request("https://jsonplaceholder.typicode.com/posts/3")
              }
            >
              Post 4
            </a>
          </p>
        </div>

        <div className={styles.grid}>
          <pre>
            {response
              ? JSON.stringify(response, null, 2)
              : "First make a request"}
          </pre>
        </div>
      </main>
    </div>
  );
}
